#define COMMON_GL_MAGS            \
"M319_HE_Grenade_Shell",          \
"M319_HEDP_Grenade_Shell",		  \
"M319_HEAT_Grenade_Shell",        \
"M319_Buckshot",                  \
"M319_Smoke",                     \
"M319_Smoke_Orange",              \
"M319_Smoke_Green",               \
"M319_Smoke_Red",                 \
"1Rnd_HE_Grenade_shell",          \
"UGL_FlareWhite_F",               \
"UGL_FlareGreen_F",               \
"UGL_FlareRed_F",                 \
"UGL_FlareYellow_F",              \
"UGL_FlareCIR_F",                 \
"1Rnd_Smoke_Grenade_shell",       \
"1Rnd_SmokeRed_Grenade_shell",    \
"1Rnd_SmokeGreen_Grenade_shell",  \
"1Rnd_SmokeYellow_Grenade_shell", \
"1Rnd_SmokePurple_Grenade_shell", \
"1Rnd_SmokeBlue_Grenade_shell",   \
"1Rnd_SmokeOrange_Grenade_shell", \
"3Rnd_UGL_FlareWhite_F",          \
"3Rnd_UGL_FlareGreen_F",          \
"3Rnd_UGL_FlareRed_F",            \
"3Rnd_UGL_FlareYellow_F",         \
"3Rnd_UGL_FlareCIR_F",            \
"3Rnd_Smoke_Grenade_shell",       \
"3Rnd_SmokeRed_Grenade_shell",    \
"3Rnd_SmokeGreen_Grenade_shell",  \
"3Rnd_SmokeYellow_Grenade_shell", \
"3Rnd_SmokePurple_Grenade_shell", \
"3Rnd_SmokeBlue_Grenade_shell",   \
"3Rnd_SmokeOrange_Grenade_shell", \
"OPTRE_signalSmokeB",             \
"OPTRE_signalSmokeG",             \
"OPTRE_signalSmokeO",             \
"OPTRE_signalSmokeP",             \
"OPTRE_signalSmokeR",             \
"OPTRE_signalSmokeY",             \
"12th_40mm_heat"