name = "12th MEU Assets"
prefix = "12thmd_assets"
author = "Kelp"

[files]
include = [
    "mod.cpp",
    "logo.paa",
    "README.md",
    "LICENSE",
    "*.pbo"
]

[version]
major = 6
minor = 0
patch = 0
build = 0
git_hash = 0
